export const dummyMovies = [
  {
    Title: "Blade Runner",
    Year: "1982",
    imdbID: "tt0083658",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOWQ4YTBmNTQtMDYxMC00NGFjLTkwOGQtNzdhNmY1Nzc1MzUxXkEyXkFqcGc@._V1_SX300.jpg",
  },
  {
    Title: "Blade Runner 2049",
    Year: "2017",
    imdbID: "tt1856101",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_QL75_UX380_CR0,0,380,562_.jpg",
  },
  {
    Title: "Blade",
    Year: "1998",
    imdbID: "tt0120611",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzAzMmY3OWMtNDgyMS00Y2U4LTlmM2UtY2YwMmM0MDI5ODJmXkEyXkFqcGc@._V1_SX300.jpg",
  },
  {
    Title: "Blade II",
    Year: "2002",
    imdbID: "tt0187738",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMGE5ZmY2NzEtZTEyMi00MWIyLThmOWYtYzJkOTQ0Y2U3ZWU1XkEyXkFqcGc@._V1_SX300.jpg",
  },
  {
    Title: "Blade: Trinity",
    Year: "2004",
    imdbID: "tt0359013",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjE0Nzg2MzI3MF5BMl5BanBnXkFtZTYwMjExODQ3._V1_SX300.jpg",
  },
  {
    Title: "Sling Blade",
    Year: "1996",
    imdbID: "tt0117666",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDM5MjhhMDgtMmVmYy00ODNlLWI1OGMtMzAzNmY5OGRmNjk0XkEyXkFqcGc@._V1_SX300.jpg",
  },
  {
    Title: "Dragon Blade",
    Year: "2015",
    imdbID: "tt3672840",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMTk0MjgxOTQ5MF5BMl5BanBnXkFtZTgwODA3NTUwNjE@._V1_SX300.jpg",
  },
  {
    Title: "Blade of the Immortal",
    Year: "2017",
    imdbID: "tt5084170",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZjUzODFjYmYtYzA0Yi00ODk2LTg2OGUtYWExYjc2NzYyNTc1XkEyXkFqcGc@._V1_SX300.jpg",
  },
  {
    Title: "Shinobi: Heart Under Blade",
    Year: "2005",
    imdbID: "tt0475723",
    Type: "movie",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjQ0ZDgzMDUtOTE5MC00MTUwLWFmM2EtOGRiNzQ3NWNmMWQzXkEyXkFqcGc@._V1_SX300.jpg",
  },
  {
    Title: "Fate/stay night [Unlimited Blade Works]",
    Year: "2014–2015",
    imdbID: "tt3621796",
    Type: "series",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BZTNmZWI3ZWYtNjkzYi00ZTFkLWI0MzctMjc2YzlmNGRkNzRiXkEyXkFqcGc@._V1_SX300.jpg",
  },
];

export const movieDetails = [
  {
    Title: "Blade Runner",
    Year: "1982",
    Rated: "R",
    Released: "25 Jun 1982",
    Runtime: "117 min",
    Genre: "Action, Drama, Sci-Fi",
    Director: "Ridley Scott",
    Writer: "Hampton Fancher, David Webb Peoples, Philip K. Dick",
    Actors: "Harrison Ford, Rutger Hauer, Sean Young",
    Plot: "A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.",
    Language: "English, German, Cantonese, Japanese, Hungarian, Arabic, Korean",
    Country: "United States, United Kingdom, Hong Kong",
    Awards: "Nominated for 2 Oscars. 13 wins & 22 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BOWQ4YTBmNTQtMDYxMC00NGFjLTkwOGQtNzdhNmY1Nzc1MzUxXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "89%",
      },
      {
        Source: "Metacritic",
        Value: "84/100",
      },
    ],
    Metascore: "84",
    imdbRating: "8.1",
    imdbVotes: "876,371",
    imdbID: "tt0083658",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$32,914,489",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Blade Runner 2049",
    Year: "2017",
    Rated: "R",
    Released: "06 Oct 2017",
    Runtime: "164 min",
    Genre: "Action, Drama, Mystery",
    Director: "Denis Villeneuve",
    Writer: "Hampton Fancher, Michael Green, Philip K. Dick",
    Actors: "Harrison Ford, Ryan Gosling, Ana de Armas",
    Plot: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    Language: "English",
    Country: "Spain, Canada, United States",
    Awards: "Won 2 Oscars. 100 wins & 164 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_QL75_UX380_CR0,0,380,562_.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "88%",
      },
      {
        Source: "Metacritic",
        Value: "81/100",
      },
    ],
    Metascore: "81",
    imdbRating: "8.0",
    imdbVotes: "751,317",
    imdbID: "tt1856101",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$92,071,675",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Blade",
    Year: "1998",
    Rated: "R",
    Released: "21 Aug 1998",
    Runtime: "120 min",
    Genre: "Action, Horror, Sci-Fi",
    Director: "Stephen Norrington",
    Writer: "David S. Goyer",
    Actors: "Wesley Snipes, Stephen Dorff, Kris Kristofferson",
    Plot: "A half-vampire, half-mortal man becomes a protector of the mortal race, while slaying evil vampires.",
    Language: "English, Russian, Serbian",
    Country: "United States",
    Awards: "5 wins & 11 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNzAzMmY3OWMtNDgyMS00Y2U4LTlmM2UtY2YwMmM0MDI5ODJmXkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "7.1/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "59%",
      },
      {
        Source: "Metacritic",
        Value: "47/100",
      },
    ],
    Metascore: "47",
    imdbRating: "7.1",
    imdbVotes: "327,850",
    imdbID: "tt0120611",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$70,087,718",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Blade II",
    Year: "2002",
    Rated: "R",
    Released: "22 Mar 2002",
    Runtime: "117 min",
    Genre: "Action, Horror, Sci-Fi",
    Director: "Guillermo del Toro",
    Writer: "Marv Wolfman, Gene Colan, David S. Goyer",
    Actors: "Wesley Snipes, Kris Kristofferson, Ron Perlman",
    Plot: "Blade forms an uneasy alliance with the vampire council in order to combat the Reapers, who are feeding on vampires.",
    Language: "English, Romanian, Czech",
    Country: "United States, Germany",
    Awards: "6 wins & 10 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMGE5ZmY2NzEtZTEyMi00MWIyLThmOWYtYzJkOTQ0Y2U3ZWU1XkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "6.7/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "57%",
      },
      {
        Source: "Metacritic",
        Value: "52/100",
      },
    ],
    Metascore: "52",
    imdbRating: "6.7",
    imdbVotes: "251,178",
    imdbID: "tt0187738",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$82,348,319",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },

  {
    Title: "Blade: Trinity",
    Year: "2004",
    Rated: "R",
    Released: "08 Dec 2004",
    Runtime: "113 min",
    Genre: "Action, Horror, Sci-Fi",
    Director: "David S. Goyer",
    Writer: "David S. Goyer, Marv Wolfman, Gene Colan",
    Actors: "Wesley Snipes, Kris Kristofferson, Parker Posey",
    Plot: "Blade, now a wanted man by the FBI, must join forces with the Nightstalkers to face his most challenging enemy yet: Dracula.",
    Language: "English, Esperanto",
    Country: "United States",
    Awards: "1 nomination total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BMjE0Nzg2MzI3MF5BMl5BanBnXkFtZTYwMjExODQ3._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "5.8/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "24%",
      },
      {
        Source: "Metacritic",
        Value: "38/100",
      },
    ],
    Metascore: "38",
    imdbRating: "5.8",
    imdbVotes: "200,173",
    imdbID: "tt0359013",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$52,411,906",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
  {
    Title: "Sling Blade",
    Year: "1996",
    Rated: "R",
    Released: "14 Mar 1997",
    Runtime: "135 min",
    Genre: "Drama",
    Director: "Billy Bob Thornton",
    Writer: "Billy Bob Thornton",
    Actors: "Billy Bob Thornton, Dwight Yoakam, J.T. Walsh",
    Plot: "Karl Childers, a simple man hospitalized since his childhood murder of his mother and her lover, is released to start a new life in a small town.",
    Language: "English",
    Country: "United States",
    Awards: "Won 1 Oscar. 14 wins & 15 nominations total",
    Poster:
      "https://m.media-amazon.com/images/M/MV5BNDM5MjhhMDgtMmVmYy00ODNlLWI1OGMtMzAzNmY5OGRmNjk0XkEyXkFqcGc@._V1_SX300.jpg",
    Ratings: [
      {
        Source: "Internet Movie Database",
        Value: "8.0/10",
      },
      {
        Source: "Rotten Tomatoes",
        Value: "96%",
      },
      {
        Source: "Metacritic",
        Value: "85/100",
      },
    ],
    Metascore: "85",
    imdbRating: "8.0",
    imdbVotes: "104,179",
    imdbID: "tt0117666",
    Type: "movie",
    DVD: "N/A",
    BoxOffice: "$24,444,121",
    Production: "N/A",
    Website: "N/A",
    Response: "True",
  },
];
